# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20170928_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_status_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1),
        ),
    ]
